config/routes.rb
FallingfruitWebapp::Application.routes.draw do

  resources :locations do
    collection do
      get 'import'
      post 'import'
      get 'cluster'
      get 'markers'
      get 'data'
    end
  end

  resources :types

  resources :regions

  match 'about' => 'pages#about'
  match 'data' => 'pages#data'

  devise_for :admins
  resources :admins do
    member do
      get 'approve'
    end
  end

  resources :imports

  match 'locations/:id/infobox' => 'locations#infobox'

  root :to => 'locations#index'

end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_filter :authenticate_admin!

  # GET /types
  # GET /types.json
  def index
    @types = Type.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @types }
      format.csv { render csv: @types }
    end
  end

  # GET /types/new
  # GET /types/new.json
  def new
    @type = Type.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @type }
    end
  end

  # GET /types/1/edit
  def edit
    @type = Type.find(params[:id])
  end

  # POST /types
  # POST /types.json
  def create
    @type = Type.new(params[:type])

    respond_to do |format|
      if @type.save
        format.html { redirect_to types_path, notice: 'Type was successfully created.' }
        format.json { render json: @type, status: :created, location: @type }
      else
        format.html { render action: "new" }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /types/1
  # PUT /types/1.json
  def update
    @type = Type.find(params[:id])

    respond_to do |format|
      if @type.update_attributes(params[:type])
        format.html { redirect_to types_path, notice: 'Type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type = Type.find(params[:id])
    @type.destroy

    respond_to do |format|
      format.html { redirect_to types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/types/_form.html.erb
<%= form_for @type, :html => { :multipart => true }  do |f| %>
  <% if @type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% @type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :synonyms %><br />
    <span class="subtext">comma-separated list, e.g., Foo, Bar, Baz</span><br>
    <%= f.text_field :synonyms %>
  </div>
  <div class="field">
    <%= f.label :scientific_name %><br />
    <%= f.text_field :scientific_name %>
  </div>
  <div class="field">
    <%= f.label :scientific_synonyms %><br />
    <%= f.text_field :scientific_synonyms %>
  </div>
  <div class="field">
    <%= f.label "USDA symbol" %><br />
    <%= f.text_field :usda_symbol %><br>
    <span class="subtext">See <a href="http://plants.usda.gov/classification.html">here</a>.</span>
  </div>
  <div class="field">
    <%= f.label :wikipedia_url %><br />
    <%= f.text_field :wikipedia_url %>
  </div>
  <div class="field">
    <%= f.label :edibility %><br />
    <%= f.select(:edability,Type::Edabilities.collect{ |k,v| [v,k] },:include_blank => true) %>
  </div>
  <div class="field">
    <%= f.label :custom_marker %><br />
    <span class="subtext">Currently unused...</span><br>
    <%= f.file_field :marker %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/types/edit.html.erb
<h1>Editing type</h1>

<%= render 'form' %>

app/views/types/index.html.erb
<h1>Source Types</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Scientific Name</th>
    <th>Edibility</th>
    <th>USDA Symbol</th>
    <th></th>
    <th></th>
  </tr>

<% @types.each do |type| %>
  <tr>
    <td>
    <% unless type.wikipedia_url.nil? %>
     <a href="<%= raw type.wikipedia_url %>" target="_blank"><%= type.name %></a>
    <% else %>
     <%= type.name %>
    <% end %>
    <%= "(#{type.synonyms})" unless type.synonyms.nil? or type.synonyms == ""%>
    </td>
    <td><em><%= type.scientific_name %> <%= "(#{type.scientific_synonyms})" unless type.scientific_synonyms.nil? or type.scientific_synonyms == "" %></em></td>
    <td><%= Type::Edabilities[type.edability] unless type.edability.nil? %>
    <td><%= raw !type.usda_symbol.nil? ? "<a href=\"http://plants.usda.gov/java/profile?symbol=#{type.usda_symbol}\">#{type.usda_symbol}</a>" : "?"%></em></td>

    <td><%= link_to 'Edit', edit_type_path(type) %></td>
    <td><%= link_to 'Destroy', type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Type', new_type_path %>

app/views/types/new.html.erb
<h1>New type</h1>

<%= render 'form' %>