config/routes.rb
FallingfruitWebapp::Application.routes.draw do

  resources :locations do
    collection do
      get 'import'
      post 'import'
      get 'cluster'
      get 'markers'
      get 'data'
    end
  end

  resources :types

  resources :regions

  match 'about' => 'pages#about'
  match 'data' => 'pages#data'

  devise_for :admins
  resources :admins do
    member do
      get 'approve'
    end
  end

  resources :imports

  match 'locations/:id/infobox' => 'locations#infobox'

  root :to => 'locations#index'

end

app/models/import.rb
class Import < ActiveRecord::Base
  attr_accessible :name, :url, :comments, :autoload, :muni
  validates :name, :presence => true
  has_many :locations
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  before_filter :authenticate_admin!

  def index
    @imports = Import.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @imports }
    end
  end

  def edit
    @import = Import.find(params[:id])
  end

  def update
    @import = Import.find(params[:id])

    respond_to do |format|
      if @import.update_attributes(params[:import])
        format.html { redirect_to imports_path, notice: 'Import was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @import.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @import = Import.find(params[:id])
    @import.locations.each{ |l|
      l.locations_types.each{ |lt|
        LocationsType.delete(lt.id)
      }
      Location.delete(l.id)
    }
    @import.destroy
    respond_to do |format|
      format.html { redirect_to imports_url }
      format.json { head :no_content }
    end
  end
end

app/views/imports/_form.html.erb
<%= form_for @import do |f| %>
  <% if @import.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% @import.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :comments %><br />
    <%= f.text_area :comments %><br>
  </div>

  <div class="field">
    <%= f.label :autoload %><br />
    <%= f.check_box :autoload %>
  </div>
  <div class="field">
    <%= f.label :municipal %><br />
    <%= f.check_box :muni %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/imports/edit.html.erb
<h1>Editing import</h1>

<%= render 'form' %>

app/views/imports/index.html.erb
<h1>Imports</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Locations</th>
    <th>Autoload</th>
    <th>Muni</th>
    <th>Created At</th>
    <th></th>
    <th></th>
  </tr>

<% @imports.each do |import| %>
  <tr>
    <td><%= import.name %></td>
    <td><%= import.locations.count %></td>
    <td><%= import.autoload ? "X" : "" %></td>
    <td><%= import.muni ? "X" : "" %></td>
    <td><%= import.created_at %></td>
    <td><%= link_to 'Edit', edit_import_path(import) %></td>
    <td><%= link_to 'Destroy', import, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>